In [1]:
!pip install gym
!pip install keras
!pip install keras-rl2

  Created wheel for gym: filename=gym-0.18.3-py3-none-any.whl size=1657516 sha256=0b78e7693839a41d00322801bde06e264e82c7b9612a02b80b772b0be7d0b195
  Stored in directory: c:\users\mb16\appdata\local\pip\cache\wheels\b3\03\54\9141c232861b89be935b37bdde0ea5ab472f5e18fc20623aed
Successfully built gym
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.2
    Uninstalling numpy-1.20.2:
      Successfully uninstalled numpy-1.20.2
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.5.0
    Uninstalling tensorflow-estimator-2.5.0:
      Successfully uninstalled tensorflow-estimator-2.5.0
  Attempting uninstall: scipy
    Found existing installation: scipy 1.6.2
    Uninstalling scipy-1.6.2:
      Successfully uninstalled scipy-1.6.2
  Attempting uninstall: gast
    Found existing installation: gast 0.4.0
    Uninstalling gast-0.4.0:
      Successfully uninstalled gast-0.4.0


In [3]:
import gym 
import random
import tensorflow as tf 
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from rl.agents import DQNAgent
from rl.policy import BoltzmannQPolicy
from rl.memory import SequentialMemory

In [4]:
print(tf.__version__)

2.3.0


https://gym.openai.com/
https://gym.openai.com/docs/
____________________________________________________________________________________________________________________________

https://gym.openai.com/envs/CartPole-v1/
CartPole-v1
A pole is attached by an un-actuated joint to a cart, which moves along a frictionless track. The system is controlled by applying a force of +1 or -1 to the cart. The pendulum starts upright, and the goal is to prevent it from falling over. A reward of +1 is provided for every timestep that the pole remains upright. The episode ends when the pole is more than 15 degrees from vertical, or the cart moves more than 2.4 units from the center.
_____________________________________________________________________________________________________________________________

here’s a bare minimum example of getting something running. This will run an instance 
of the CartPole-v0 environment for 1000 timesteps, rendering the environment at each step.
You should see a window pop up rendering the classic cart-pole problem:

In [5]:
env = gym.make("CartPole-v0")
print(env)
print(type(env))


<TimeLimit<CartPoleEnv<CartPole-v0>>>
<class 'gym.wrappers.time_limit.TimeLimit'>


In [6]:
env.reset()
for _ in range(10000):
    env.render()
    n_state, reward, done, info = env.step(env.action_space.sample()) # take a random action
    print("n_state = " , n_state)
    print("info " , info)
     
    if done == True :
        break 
        
env.reset()
env.close()

n_state =  [-0.0242742   0.17965875  0.03599208 -0.33056074]
info  {}
n_state =  [-0.02068102 -0.01595656  0.02938087 -0.02674841]
info  {}
n_state =  [-0.02100015  0.17873199  0.0288459  -0.31001848]
info  {}
n_state =  [-0.01742551  0.37343134  0.02264553 -0.59346647]
info  {}
n_state =  [-0.00995689  0.17799984  0.0107762  -0.29373717]
info  {}
n_state =  [-0.00639689  0.37296651  0.00490146 -0.58300205]
info  {}
n_state =  [ 0.00106244  0.56801945 -0.00675858 -0.87413692]
info  {}
n_state =  [ 0.01242283  0.37299003 -0.02424132 -0.58358649]
info  {}
n_state =  [ 0.01988263  0.56844305 -0.03591305 -0.88380613]
info  {}
n_state =  [ 0.03125149  0.76403379 -0.05358917 -1.18755923]
info  {}
n_state =  [ 0.04653217  0.95980802 -0.07734036 -1.49654669]
info  {}
n_state =  [ 0.06572833  1.15578031 -0.10727129 -1.8123418 ]
info  {}
n_state =  [ 0.08884393  0.96200445 -0.14351813 -1.55482607]
info  {}
n_state =  [ 0.10808402  0.76886438 -0.17461465 -1.31014412]
info  {}
n_state =  [ 0.12346

In [7]:
#more proper way 
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        print("actions "  , action)
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[ 0.04257053 -0.01093887  0.01739871  0.02438075]
actions  1
[ 0.04235175  0.18392931  0.01788633 -0.26276231]
actions  1
[ 0.04603034  0.37879144  0.01263108 -0.54975045]
actions  0
[ 0.05360617  0.18349436  0.00163607 -0.25311477]
actions  0
[ 0.05727606 -0.01165091 -0.00342622  0.04008375]
actions  1
[ 0.05704304  0.18352    -0.00262455 -0.25367821]
actions  1
[ 0.06071344  0.37867933 -0.00769811 -0.54718781]
actions  0
[ 0.06828703  0.18366638 -0.01864187 -0.25694026]
actions  0
[ 0.07196035 -0.01118453 -0.02378068  0.02980492]
actions  0
[ 0.07173666 -0.20595753 -0.02318458  0.31489094]
actions  1
[ 0.06761751 -0.01051312 -0.01688676  0.01498747]
actions  0
[ 0.06740725 -0.20538888 -0.01658701  0.30229495]
actions  0
[ 0.06329947 -0.40027054 -0.01054111  0.58970089]
actions  1
[ 0.05529406 -0.20500259  0.00125291  0.2937162 ]
actions  1
[ 0.05119401 -0.00989853  0.00712723  0.00142869]
actions  0
[ 0.05099604 -0.20512196  0.00715581  0.2963518 ]
actions  0
[ 0.0468936  -0.40034519

[-0.02462902  0.20653806  0.00950365 -0.24540662]
actions  0
[-0.02049826  0.01128167  0.00459551  0.05025877]
actions  0
[-0.02027262 -0.18390588  0.00560069  0.34438807]
actions  0
[-0.02395074 -0.37910705  0.01248845  0.63883184]
actions  1
[-0.03153288 -0.18416144  0.02526509  0.35010773]
actions  0
[-0.03521611 -0.37963342  0.03226724  0.65064927]
actions  0
[-0.04280878 -0.5751896   0.04528023  0.95331576]
actions  0
[-0.05431257 -0.77089057  0.06434654  1.25987418]
actions  0
[-0.06973038 -0.96677396  0.08954403  1.57199602]
actions  1
[-0.08906586 -0.77282724  0.12098395  1.30853225]
actions  1
[-0.10452241 -0.57942801  0.14715459  1.05603649]
actions  1
[-0.11611097 -0.38653005  0.16827532  0.8129242 ]
actions  1
[-0.12384157 -0.19406316  0.1845338   0.57754153]
actions  0
[-0.12772283 -0.3912265   0.19608464  0.92221091]
actions  1
Episode finished after 17 timesteps
[-0.03998464 -0.01741474 -0.04135226 -0.04150308]
actions  0
[-0.04033293 -0.21192006 -0.04218232  0.23785138]

[-0.01280998  0.03672421 -0.0368021  -0.19692623]
actions  0
[-0.0120755  -0.15785254 -0.04074062  0.0839239 ]
actions  1
[-0.01523255  0.03782902 -0.03906214 -0.2213293 ]
actions  1
[-0.01447597  0.23348691 -0.04348873 -0.52607361]
actions  0
[-0.00980623  0.03900302 -0.0540102  -0.24740525]
actions  0
[-0.00902617 -0.15530764 -0.05895831  0.02776444]
actions  0
[-0.01213232 -0.3495367  -0.05840302  0.30127811]
actions  0
[-0.01912305 -0.54377972 -0.05237746  0.57498514]
actions  0
[-0.02999865 -0.73812978 -0.04087775  0.85071851]
actions  1
[-0.04476124 -0.542475   -0.02386338  0.54546679]
actions  0
[-0.05561074 -0.73725365 -0.01295405  0.83053642]
actions  0
[-0.07035582 -0.93219617  0.00365668  1.11911728]
actions  1
[-0.08899974 -0.73712238  0.02603903  0.82758362]
actions  1
[-0.10374219 -0.54236596  0.0425907   0.54320263]
actions  1
[-0.11458951 -0.34786763  0.05345475  0.26423758]
actions  0
[-0.12154686 -0.5437102   0.0587395   0.57329004]
actions  0
[-0.13242106 -0.7396044 

[-0.02012731 -0.04206762  0.04564635  0.10066376]
actions  0
[-0.02096867 -0.23781302  0.04765963  0.4073914 ]
actions  0
[-0.02572493 -0.43357722  0.05580745  0.71471088]
actions  0
[-0.03439647 -0.62942549  0.07010167  1.02442481]
actions  0
[-0.04698498 -0.82540744  0.09059017  1.33826872]
actions  0
[-0.06349313 -1.02154596  0.11735554  1.65786721]
actions  0
[-0.08392405 -1.2178247   0.15051289  1.98468361]
actions  1
[-0.10828054 -1.02457058  0.19020656  1.74216364]
actions  1
Episode finished after 16 timesteps
[-0.0147904  -0.00676817 -0.02652121 -0.01817807]
actions  0
[-0.01492576 -0.20149993 -0.02688477  0.26602054]
actions  1
[-0.01895576 -0.00600479 -0.02156436 -0.03501937]
actions  1
[-0.01907586  0.18941965 -0.02226475 -0.33442732]
actions  0
[-0.01528746 -0.00537846 -0.02895329 -0.04884786]
actions  0
[-0.01539503 -0.20007354 -0.02993025  0.23456128]
actions  0
[-0.0193965  -0.39475535 -0.02523902  0.51765503]
actions  1
[-0.02729161 -0.19928729 -0.01488592  0.21712684]

In [8]:
import gym
env = gym.make('CartPole-v0')
print(env.action_space)
#> Discrete(2)
print(env.observation_space)
#> Box(4,)

actions = env.action_space.n
states = env.observation_space.shape[0]
print(actions)
print(states)


Discrete(2)
Box(-3.4028234663852886e+38, 3.4028234663852886e+38, (4,), float32)
2
4


In [9]:
def build_model(states, actions):
    model = Sequential()
    model.add(Flatten(input_shape=(1,states)))
    model.add(Dense(24, activation='relu'))
    model.add(Dense(24, activation='relu'))
    model.add(Dense(actions, activation='linear'))
    return model

In [10]:
states = states = env.observation_space.shape[0]
actions = env.action_space.n


In [11]:
model = build_model(states, actions)

Build Agent with Keras-RL
https://keras-rl.readthedocs.io/en/latest/

In [12]:
def build_agent(model, actions):
    policy = BoltzmannQPolicy()
    memory = SequentialMemory(limit=50000, window_length=1)
    dqn = DQNAgent(model=model, memory=memory, policy=policy, 
                  nb_actions=actions, nb_steps_warmup=10, target_model_update=1e-2)
    return dqn

In [13]:
dqn = build_agent(model, actions)
dqn.compile(Adam(lr=1e-3), metrics=['mae'])
dqn.fit(env, nb_steps=50000, visualize=False, verbose=1)

Training for 50000 steps ...
Interval 1 (0 steps performed)
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
    1/10000 [..............................] - ETA: 5:58 - reward: 1.0000

C:\Users\MB16\reinforce\envs\lib\site-packages\rl\memory.py:37: UserWarning: Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!
  warnings.warn('Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!')


10000/10000 [==============================] - 49s 5ms/step - reward: 1.0000
108 episodes - episode_reward: 92.130 [10.000, 200.000] - loss: 3.551 - mae: 19.425 - mean_q: 39.323

Interval 2 (10000 steps performed)
10000/10000 [==============================] - 49s 5ms/step - reward: 1.0000
50 episodes - episode_reward: 197.980 [169.000, 200.000] - loss: 10.360 - mae: 42.164 - mean_q: 84.944

Interval 3 (20000 steps performed)
10000/10000 [==============================] - 50s 5ms/step - reward: 1.0000
52 episodes - episode_reward: 191.519 [161.000, 200.000] - loss: 8.466 - mae: 44.789 - mean_q: 90.102

Interval 4 (30000 steps performed)
10000/10000 [==============================] - 52s 5ms/step - reward: 1.0000
54 episodes - episode_reward: 187.833 [153.000, 200.000] - loss: 5.587 - mae: 41.979 - mean_q: 84.296

Interval 5 (40000 steps performed)
10000/10000 [==============================] - 53s 5ms/step - reward: 1.0000
done, took 253.446 seconds


In [14]:
dqn.test(env, nb_episodes=15, visualize=False)

Testing for 15 episodes ...
Episode 1: reward: 200.000, steps: 200
Episode 2: reward: 198.000, steps: 198
Episode 3: reward: 200.000, steps: 200
Episode 4: reward: 200.000, steps: 200
Episode 5: reward: 200.000, steps: 200
Episode 6: reward: 200.000, steps: 200
Episode 7: reward: 200.000, steps: 200
Episode 8: reward: 200.000, steps: 200
Episode 9: reward: 200.000, steps: 200
Episode 10: reward: 200.000, steps: 200
Episode 11: reward: 200.000, steps: 200
Episode 12: reward: 200.000, steps: 200
Episode 13: reward: 200.000, steps: 200
Episode 14: reward: 200.000, steps: 200
Episode 15: reward: 197.000, steps: 197


In [15]:
dqn.save_weights('cartpole_trained1.h5f', overwrite=True)

In [16]:
del model
del dqn
del env

In [2]:
env = gym.make('CartPole-v0')
actions = env.action_space.n
states = env.observation_space.shape[0]
model = build_model(states, actions)
dqn = build_agent(model, actions)
dqn.compile(Adam(lr=1e-3), metrics=['mae'])

NameError: name 'build_model' is not defined

In [52]:
dqn.load_weights('dqn_weights.h5f')

In [ ]:
dqn.test(env, nb_episodes=5, visualize=False)