In [1]:
import gym 
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
import os

In [2]:
environment_name = "CarRacing-v0"

In [4]:
env = gym.make(environment_name)

In [5]:
env??

In [5]:

episodes = 1
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)
        score+=reward
    print('Episode:{} Score:{}'.format(episode, score))
env.close()

Track generation: 1099..1378 -> 279-tiles track
Episode:1 Score:-28.05755395683485



https://gym.openai.com/envs/CarRacing-v0/

"""
Easiest continuous control task to learn from pixels, a top-down racing
environment.
Discrete control is reasonable in this environment as well, on/off
discretization is fine.
State consists of STATE_W x STATE_H pixels.
The reward is -0.1 every frame and +1000/N for every track tile visited, where
N is the total number of tiles visited in the track. For example, if you have
finished in 732 frames, your reward is 1000 - 0.1*732 = 926.8 points.
The game is solved when the agent consistently gets 900+ points. The generated
track is random every episode.
The episode finishes when all the tiles are visited. The car also can go
outside of the PLAYFIELD -  that is far off the track, then it will get -100
and die.
Some indicators are shown at the bottom of the window along with the state RGB
buffer. From left to right: the true speed, four ABS sensors, the steering
wheel position and gyroscope.
To play yourself (it's rather fast for humans), type:
python gym/envs/box2d/car_racing.py
Remember it's a powerful rear-wheel drive car -  don't press the accelerator
and turn at the same time.
Created by Oleg Klimov. Licensed on the same terms as the rest of OpenAI Gym.
"""
https://github.com/openai/gym/blob/master/gym/envs/box2d/car_racing.py

In [6]:
action = env.action_space
print(action)
print(action.sample())

#steer, gas, brake


Box(-1.0, 1.0, (3,), float32)
[0.3656063  0.21270551 0.51143247]


In [7]:
action = env.action_space.sample()
print(env.step(action))

(array([[[102, 204, 102],
        [102, 229, 102],
        [102, 229, 102],
        ...,
        [102, 204, 102],
        [102, 204, 102],
        [102, 204, 102]],

       [[102, 204, 102],
        [102, 229, 102],
        [102, 229, 102],
        ...,
        [102, 204, 102],
        [102, 204, 102],
        [102, 204, 102]],

       [[102, 204, 102],
        [102, 204, 102],
        [102, 229, 102],
        ...,
        [102, 204, 102],
        [102, 204, 102],
        [102, 204, 102]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]

In [10]:
env.close()

In [9]:
env.reset()

Track generation: 1221..1530 -> 309-tiles track


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [11]:
n_state, reward, done, info = env.step(action)

In [12]:
env.close()

In [13]:
type(n_state) , type(reward) , type(done) , type(info)

(numpy.ndarray, float, bool, dict)

In [14]:
n_state.shape

(96, 96, 3)

In [15]:
reward , done , info

(6.393506493506494, False, {})

In [16]:
model = PPO('MlpPolicy', env, verbose=1)


Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.


In [17]:
model.learn(total_timesteps=1000)

Track generation: 1084..1367 -> 283-tiles track
Track generation: 1163..1458 -> 295-tiles track
Track generation: 1187..1488 -> 301-tiles track
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 1e+03    |
|    ep_rew_mean     | -56.5    |
| time/              |          |
|    fps             | 137      |
|    iterations      | 1        |
|    time_elapsed    | 14       |
|    total_timesteps | 2048     |
---------------------------------


In [18]:
env.close()

In [19]:
model.save("self-driv")

In [21]:
load_model = PPO.load("self-driv", env)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.


In [23]:
load_model??

In [28]:
obs = env.reset()
while True:
    action, _states = load_model.predict(obs)
    obs, rewards, done, info = env.step(action)
    env.render()
    if done: 
        print('info', info)
        break
env.close()            

Track generation: 1154..1449 -> 295-tiles track
retry to generate track (normal if there are not manyinstances of this message)
Track generation: 1136..1424 -> 288-tiles track
info {'TimeLimit.truncated': True}


In [29]:
env.close()